version: '3'
services:
#  app:
#    build:
#      context: ../../
#      dockerfile: ./infrastructure/docker/Dockerfile
#    image: workwiz
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: workwiz
      MYSQL_USER: bbutler
      MYSQL_PASSWORD: not(password)
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: