name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'

      - name: Build and test Spring-boot App module
        run: |
          cd app
          ./mvnw clean verify

      - name: Build and test React/Next.js UI module
        run: |
          cd ui
          npm ci
          npm run build
          npm run test

      - name: Upload JaCoCo coverage to CodeCov
        uses: codecov/codecov-action@v4
        with:
          files: ./app/target/site/jacoco/jacoco.xml
          flags: app
          name: Spring-boot App
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload lcov coverage to CodeCov
        uses: codecov/codecov-action@v4
        with:
          files: ./ui/coverage/lcov.info
          flags: ui
          name: React/Next.js UI
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
